---
# tasks file for inmotion.ultrastack_php

- name: (PHP-FPM) Set and santitize facts
  include: facts.yml

- name: (PHP-FPM) Include os_family tasks
  include: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
      - RedHat
  when: ansible_os_family in targets

- name: (PHP-FPM) Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/run/php

- name: (PHP-FPM) Configure php.ini
  template:
    src: etc/php.ini.j2
    dest: "{{ php_config_ini_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart php-fpm

- name: (PHP-FPM) Check if Apache dirs are present
  stat:
    path: "{{ apache_config_path }}"
  register: apache

- name: (PHP-FPM) Configure Apache PHP settings
  template:
    src: etc/httpd/conf.d/php.conf.j2
    dest: "{{ apache_config_path }}/php.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart php-fpm
  when: apache.stat.exists

- name: (PHP-FPM) Start and enable php-fpm service
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: true

#- name: Get PHP version
#  command: php -v
#  register: php_version_out

#- debug:
#    var: "{{ php_version_out }}"
