---
# tasks file for inmotion.ultrastack_php

- name: Set and santitize facts
  include: facts.yml

- name: Include os_family tasks
  include: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
      - RedHat
  when: ansible_os_family in targets

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/run/php

- name: Configure php.ini
  template:
    src: etc/php.ini.j2
    dest: "{{ php_config_ini_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart php-fpm

- name: Check if Apache dirs are present
  stat:
    path: "{{ apache_config_path }}"
  register: apache

- name: Configure Apache PHP settings
  template:
    src: etc/httpd/conf.d/php.conf.j2
    dest: "{{ apache_config_path }}/php.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart php-fpm
  when: apache.stat.exists

- name: Include systemd restart configuation
  include: systemd.yml
  when:  >-
    ( php_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Start and enable php-fpm service
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: true
